### ISSUE TITLE
Use of unarmed fields (*N) in DS causes incorrect colorization

### ISSUE THREAD

**Issue by JonFP** [barrettotte/vscode-ibmi-languages#103]
See the sample here:
<img width="344" alt="image" src="https://user-images.githubusercontent.com/13474625/153776113-70a9dd69-cee1-486f-aa2b-0f0f16724268.png">

Use of *N as a field name causes the line to be misidentified.  See image for example.

**Comment by barrettotte** [comment]
I think my syntax highlighter is managing to confuse those lines with fixed format comments somehow. Good find, thanks!

**Comment by barrettotte** [comment]
@JonFP Is there another example of this occurring? I can't seem to be able to reproduce this with:

```
     c* test fixed format
      *
      dcl-ds header;
         *n      char(7) Inz('Order: ');
         orderId char(6);
         *n      char(9) Inz('Product: ');
         productId char(6);
         *n      char(7) Inz('Price: ');
         price   char(9);
         *n      char(5) Inz('Qty: ');
         qty     char(5);
      end-ds;


/free
// test free format

dcl-ds header;
   *n      char(7) Inz('Order: ');
   orderId char(6);
   *n      char(9) Inz('Product: ');
   productId char(6);
   *n      char(7) Inz('Price: ');
   price   char(9);
   *n      char(5) Inz('Qty: ');
   qty     char(5);
end-ds;

/end-free

```
![image](https://user-images.githubusercontent.com/15623775/155005439-595b84b5-8a31-4bb7-9a91-4321c26ef0c4.png)
![image](https://user-images.githubusercontent.com/15623775/155005464-267e9aa4-4375-469d-9ac8-37c199e18dbc.png)

**Comment by barrettotte** [comment]
Ah that is weird, glad it seems to be working now. But, oh yeah good point; I did that without thinking. Thanks!
