### ISSUE TITLE
SQLRPGLE format highlighting does not working

### ISSUE THREAD

**Issue by MarkBoyer** [barrettotte/vscode-ibmi-languages#112]
If I have an IFS file with the .rpgle extension and full **FREE formatting, the highlighting works as expected.  If I take the same file and just rename it to have the .sqlrpgle extension and make no other changes, all highlighting is lost.  Any thoughts on what could be causing this?

TIA

**Comment by MarkBoyer** [comment]
@worksofliam that's odd, I hadn't noticed, but no, it shows as "RPG"
![Screen Shot 2022-07-07 at 9 43 40 AM](https://user-images.githubusercontent.com/3966735/177826972-54318373-ddb9-4a7c-84e7-e9d50f36b56e.png)

**Comment by worksofliam** [comment]
@MarkBoyer You have a conflicting extension. If you click it, change it to RPGLE, that might solve your problem.

**Comment by MarkBoyer** [comment]
@worksofliam perfect!  That did it.  Thank you!
