### ISSUE TITLE
Custom source types

### ISSUE THREAD

**Issue by KeanuWatts** [barrettotte/vscode-ibmi-languages#119]
Our implementation system has custom source types and as such we do not get syntax highlighting.

For example our code that is compiled as SQLRPGLE is saved as RPGSLE.
A simple configurable dictionary to interpret RPGSLE as SQLRPGLE would solve this problem.

**Comment by worksofliam** [comment]
This is something you can do and is not something that this extension would handle.

https://stackoverflow.com/questions/29973619/how-to-make-vs-code-treat-a-file-extensions-as-a-certain-language/51228725#51228725
