### ISSUE TITLE
BUG:  Color highlighting broken by entries in columns 1 - 6

### ISSUE THREAD

**Issue by JDubbTX** [barrettotte/vscode-ibmi-languages#120]
The first line of this source member has asterisks in columns 1-6.  This seems to break syntax coloring for the entire source member.
![image](https://user-images.githubusercontent.com/56802156/206510884-37f08c6b-ccca-4f1f-aa1b-c559b58728d8.png)

**Comment by barrettotte** [comment]
Thanks, should be fixed in https://github.com/barrettotte/vscode-ibmi-languages/releases/tag/v0.6.9
