### ISSUE TITLE
what debugger do you guys use for CL, RPG, etc.

### ISSUE THREAD

**Issue by obito74** [barrettotte/vscode-ibmi-languages#131]

**Comment by chrjorgensen** [comment]
@obito74 When developing in VS Code I use Code for IBM i, which integrates the IBM i debugger extension - for more information about the requirements, see here: https://halcyon-tech.github.io/docs/#/pages/developing/debug/debug


Occasionally I also use the STRDBG command, especially when debugging a batch job.
