### ISSUE TITLE
Fall 2023: PTF enhancements for 7.5 and 7.4

### ISSUE THREAD

**Issue by chrjorgensen** [barrettotte/vscode-ibmi-languages#132]
`%left`, `%right` BIF's and "enumeration" definition type:

https://ibm.biz/rpgcafe_fall_2023_bifs_left_right
https://ibm.biz/rpgcafe_fall_2023_enums

**Comment by worksofliam** [comment]
I will be working on these enhancements for vscode-rpgle in the coming weeks.
