### ISSUE TITLE
Problem in the CL configuration in IBM Languages

### ISSUE THREAD

**Issue by edoardomessa** [barrettotte/vscode-ibmi-languages#135]
Hi,
when I make this command:

![Screenshot 2023-10-25 alle 2 43 59 PM](https://github.com/barrettotte/vscode-ibmi-languages/assets/148963214/78314256-57f2-4f59-b413-9ff7ce0eb0b0)

after the /*FIRST all become comment.
Thanks.

**Comment by barrettotte** [comment]
@edoardomessa Sorry for the long wait on this. Released in https://github.com/barrettotte/vscode-ibmi-languages/releases/tag/v0.6.16
