### ISSUE TITLE
Fix single line `end-pr` and `end-ds` syntax highlighting error

### ISSUE THREAD

**Issue by barrettotte** [barrettotte/vscode-ibmi-languages#137]
The end keyword of single line declarations of `dcl-pr` and `dcl-ds` seem to have broken at some point.

Sample from `tests/issues/29.rpgle`
```
dcl-pr main extpgm('TESTR') end-pr;
```
![image](https://github.com/barrettotte/vscode-ibmi-languages/assets/15623775/6f192c1f-0a8e-4074-ae44-5cfc087962a8)

Sample from `tests/issues/115.rpgle`
```
dcl-ds prtDs len(132) end-ds;
```
![image](https://github.com/barrettotte/vscode-ibmi-languages/assets/15623775/0160267c-af08-45b2-88e0-d79519212097)

Probably some convoluted regex problem I broke without looking through prior samples.
I'll fix this while fixing a couple other reported issues.

**Comment by chrjorgensen** [comment]
@barrettotte Nice having you back! 😃
