### ISSUE TITLE
Question regarding "identifiers" in "dds.pf.tmLanguage.json"

### ISSUE THREAD

**Issue by richardm90** [barrettotte/vscode-ibmi-languages#141]
I was viewing the DDS source for a physical file the other day and noticed that the "R" in position 29 was not highlighted when the length of the field name is 10 characters long.
![image](https://github.com/barrettotte/vscode-ibmi-languages/assets/7809440/3d2495d3-8a92-42df-9472-b9d7935af52f)
If I remove the whole "identifiers" section from the syntax file then it works as expected.
![image](https://github.com/barrettotte/vscode-ibmi-languages/assets/7809440/9334b04e-472d-4bcb-8d76-04b7ad82fc44)
I couldn't see any specific documentation in the [Language Configuration Guide](https://code.visualstudio.com/api/language-extensions/language-configuration-guide) that mentioned "identifiers" so was curious as to what this definition actually does. Does anyone know?
As an aside the pattern name within the "identifiers" section is `identifier.other.dds.lf.identifiers` rather than `identifier.other.dds.pf.identifiers`.

**Comment by barrettotte** [comment]
Identifier is a term used during lexing/parsing for representing variables, parameters, user-defined functions, etc (https://en.wikipedia.org/wiki/Lexical_analysis). This term is used in the vscode docs at https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#standard-token-types-and-modifiers.

I think there may be a regex bug in the R column example you provided; I will look into this. Additionally, I agree the pattern name is wrong and is a copy/paste error that needs correcting.

**Comment by barrettotte** [comment]
Fixed in v0.6.18 - https://github.com/barrettotte/vscode-ibmi-languages/releases/tag/v0.6.18

**Comment by richardm90** [comment]
I can confirm this is working.

Is the `identifiers` section still required?
