### ISSUE TITLE
CL comment detection catching qualified special values

### ISSUE THREAD

**Issue by zkarj735** [barrettotte/vscode-ibmi-languages#143]
With a construct like `OBJ(MYLIB/*ALL)` the syntax highlighting is catching the `/*` within as the start of a comment. This marks all following code as a comment until the next comment closure `*/`

![image](https://github.com/user-attachments/assets/483ef427-169d-4ab3-a03b-0d2963aa219e)

**Comment by barrettotte** [comment]
Fixed in v0.6.18 - https://github.com/barrettotte/vscode-ibmi-languages/releases/tag/v0.6.18

**Comment by zkarj735** [comment]
Thanks, confirmed working for me.
