### ISSUE TITLE
Suggestions on how compile time arrays should be handled?

### ISSUE THREAD

**Issue by barrettotte** [barrettotte/vscode-ibmi-languages#16]
I'm decently content with compile time arrays just being a clump of data at the bottom of the program with non-sense highlighting. But, if someone has any suggestions for how they should be highlighted please let me know and I could give it a shot

**Comment by Didiv** [comment]
first **free rule must be early:
`"match": "(?i)^(\*\*(free|end-free)\b)"`

compile time arrays data:
`"begin": "^[*]{2}"`
`"end": "(E-\*-O-\*-F)"` - dummy string ))

**Comment by barrettotte** [comment]
Thanks for the suggestion, the use of that dummy string is a really good idea too.
I went slightly different from the regex you provided, but still the same general idea

```
"ctarrays": {
   "patterns": [
      {
	"name": "variable.other.rpgle.ctarrays",
	"begin": "(?=^(\\*{2})(?!free))",
	"end": "(E-\\*-O-\\*-F)",
	"patterns": [
	  {
	    "name": "string.other.rpgle.ctarray",
	    "match": "(\\s)*(\\*{2}).*"
	  }
        ]
    }
  ]
},
```

This highlights lines starting with '**' as strings and the rest as plaintext
![image](https://user-images.githubusercontent.com/15623775/78667712-6e159080-78a7-11ea-9f49-3443b5d0d6b6.png)

Let me know if that makes sense. I'm going to go ahead and include it in the new version of the extension - 0.5.1 but I am still open to changes on it.

**Comment by barrettotte** [comment]
closing this...I think it looks okay for now
