### ISSUE TITLE
Unable to install for 1.38.1

### ISSUE THREAD

**Issue by FatBobGo** [barrettotte/vscode-ibmi-languages#22]
Hi

I am not able to install the plugin, saying it is not compatible with the current version of vs code 1.38.1.

Btw, once I got the plugin installed, how to connect to back end?  Thanks.

**Comment by barrettotte** [comment]
Thanks for reaching out,

hmm i believe the current version of VS Code is version **1.44** as per https://code.visualstudio.com/updates/v1_44

In my extension I have it set for any version **>1.4.3** at
https://github.com/barrettotte/vscode-ibmi-languages/blob/master/package.json#L11
I can bump the version back to **> 1.3.8** for you if you'd like. It "shouldn't" hurt anything and would allow you to install.

As far as the backend goes, this is really only the "frontend" of an editor. It only provides syntax highlighting, but not actual source editing on IBMi. I am currently working on another extension with an API to provide that functionality, but it will be awhile.

I can share what I've been doing for the past couple months to read IBMi code:
using this python script I FTP source members based on path https://gist.github.com/barrettotte/ae24f87405279f2a7c3b99e03583c641

Example:   ```python fetchmbr.py SOMELIB.QRPGLESRC.MYPGM.RPGLE```

This is far from ideal and has trouble with EBCDIC encoding, but its been working relatively well for me while my editor API is still in development.

**Comment by barrettotte** [comment]
Sorry forgot to include this, another workflow can be detailed by this brilliant guy https://github.com/NielsLiisberg/RPG-vsCode-Getting-Started

**Comment by FatBobGo** [comment]
You are awesome! Thanks a lot for your quick reply. Will keep a close eye on your new plugin!
