### ISSUE TITLE
RPG fixed format

### ISSUE THREAD

**Issue by Didiv** [barrettotte/vscode-ibmi-languages#24]
* Incorrect color of D-section
* Incorrect color of '\' character. This is backslash character.
![image](https://user-images.githubusercontent.com/7267354/78902288-429acd80-7a82-11ea-80ed-c232ca794a5f.png)

**Comment by barrettotte** [comment]
I'm a little unfamiliar with how multiline strings work out in RPGLE, but I gave it a shot and was able to fix this example to highlight as expected. After looking through some more examples, I was able to confirm that it seemed to work in free format as well.

![image](https://user-images.githubusercontent.com/15623775/78948426-47697c80-7a96-11ea-8947-7fdf240c90b1.png)

I also applied the same method to https://github.com/barrettotte/vscode-ibmi-languages/issues/26
and it seemed to work. 

thanks for reporting!

**Comment by barrettotte** [comment]
fixed in 0.5.2
