### ISSUE TITLE
Highlights *on, *off, etc?

### ISSUE THREAD

**Issue by Didiv** [barrettotte/vscode-ibmi-languages#25]
Planning the highlight *on, *off, *loval, *hival, *start, *zero, *zeros, *blank, *blanks, *lock, etc?

**Comment by barrettotte** [comment]
As far as *ON, *OFF, etc this is currently what I see with the "monokai" color theme
![image](https://user-images.githubusercontent.com/15623775/78904271-44489f00-7a4a-11ea-9ad2-655a7fdfbc1d.png)

I'm glad you opened this one, I noticed in your other issue that in the screenshot the highlighting looked a little off and I was a bit confused.

So, I definitely need to do some testing around with other color themes.
I will make some changes and verify things look consistent across themes for the next version of the extension 0.5.2 that I'll probably end up completing this weekend

Thanks for opening this issue, I completely overlooked this.

**Comment by Didiv** [comment]
Ooh! On the Monocai theme, the highlight is visible. So this is a feature of the Light theme.

**Comment by barrettotte** [comment]
I tested everything out with color theme "light+"

I changed all regex names of ```keyword.operator``` and ```constant.other``` to ```keyword.other``` and ```constant.language```. This seems likes a step in the right direction for things looking slightly better

![image](https://user-images.githubusercontent.com/15623775/78949794-bb0d8880-7a9a-11ea-8bf0-2068529f262b.png)

Its definitely not perfect, but its a step in the right direction. Please let me know if there's anything else specific that would be nice to add for lighter color themes. 

As I've said before thank you for reporting!

**Comment by barrettotte** [comment]
Apologies if this sends another email/notification, I forgot to include this in my prior comment:

This fix and others will be part of v0.5.2 (https://github.com/barrettotte/vscode-ibmi-languages/milestone/3) I plan to finish up in the next few days

Thanks!
