### ISSUE TITLE
Outline the source

### ISSUE THREAD

**Issue by mlstoppa** [barrettotte/vscode-ibmi-languages#51]
Hi Barrett,
I am wondering whether is possible to outline procedures' names and other stuff in the OUTLINE panel. I think it will be very helpful. 
What do you think about it?

**Comment by barrettotte** [comment]
That is an awesome idea and would save a lot of headache trying to find things. 

However, this type of feature starts diving into Language Server Protocol (LSP). 
I only did some brief searching and found this [StackOverflow post](https://stackoverflow.com/questions/57131265/how-to-add-elements-to-outline-panel-in-custom-extension/57132237#57132237)

Based on that post, I believe that outline view is bundled into LSP. I believe to get an LSP extension off the ground, I'd have to make a set of parsers to be able to build some sort of syntax tree for RPG, RPGLE, CL, etc.

While this is definitely not impossible to do, it would be quite the undertaking. There are some lexers/parsers floating around for IBMi languages like [RPGLE Parser](https://github.com/rpgleparser/rpgleparser).

Implementing a LSP extension opens up a ton of awesome things such as the outline view, intellisense, and "go to symbol". Maybe one day I can start chipping away at this, but I can't say it would be anytime soon unfortunately.

Thanks for the suggestion, I would love this feature

**Comment by barrettotte** [comment]
@mlstoppa closing this issue to move discussion to https://github.com/halcyon-tech/code-for-ibmi/issues/32 .
