### ISSUE TITLE
Incorrect handling/color-coding of variables and labels with dash (-)

### ISSUE THREAD

**Issue by fisketjon** [barrettotte/vscode-ibmi-languages#58]
I tested your VS Code extension on an MI source

Dash (-) inside a variable or label is not interpreted correctly, but seems to be considered as a minus operation
e.g. MOVE-USAGE:
              CPYBLA       IO-SRCLIB,OIR-SRCLIB

Slash (/) in CMP* MI operations seems to be considered as a divide operation
e.g. CMPBLA(B)    LIBNAM,'QTEMP     '/EQ(TEMPLIB)

**Comment by barrettotte** [comment]
@fisketjon big thanks for making an issue for MI, I definitely need a lot of help identifying issues with this language.
Unfortunately the company I work for doesn't have a single MI program and by extension I've never written any MI from scratch.
So I tried to piece it together from IBM's documentation, but its quite the dense subject to read about and understand (in my opinion).

Here are the corrections to the issues you highlighted. I included them in the milestone [5.6](https://github.com/barrettotte/vscode-ibmi-languages/milestone/7) and I hope to release this version after finding maybe 1 or 2 more issues to include.

![image](https://user-images.githubusercontent.com/15623775/98743952-dfa64780-237e-11eb-9df5-141f584b39d4.png)

Please let me know if you find anything else. I know it can be annoying coming across and reporting issues, but it is a giant help to smooth out the syntax highlighting.

**Comment by barrettotte** [comment]
@fisketjon Fixed in release [v0.5.6](https://github.com/barrettotte/vscode-ibmi-languages/releases/tag/v0.5.6)
