### ISSUE TITLE
Single quote mark in comment string will incorrectly highlight block of code as a string.

### ISSUE THREAD

**Issue by CraigMcloughlin** [barrettotte/vscode-ibmi-languages#60]
![image](https://user-images.githubusercontent.com/18596216/107619324-e62caf80-6c4a-11eb-989d-d7d5823f888d.png)

**Comment by barrettotte** [comment]
@CraigMcloughlin oh yikes, thanks for reporting!

**Comment by CraigMcloughlin** [comment]
On a further check - I think it's only an issue when the comment column is used - throwing out the regex

![image](https://user-images.githubusercontent.com/18596216/107640625-76c6b800-6c6a-11eb-8535-861d7305068d.png)

**Comment by barrettotte** [comment]
@CraigMcloughlin Ah yes, the worst bug I've made on this project lol. I have to sit down on a weekend and just rewrite the RPG/RPGLE fixed format and DDS regexes. 

Seeing this bug highlight everything after as a string is further motivation to get started on it though, that's a pretty gruesome one.

**Comment by barrettotte** [comment]
@CraigMcloughlin corrected in [v0.5.6](https://github.com/barrettotte/vscode-ibmi-languages/releases/tag/v0.5.6)

**Comment by CraigMcloughlin** [comment]
Hi @barrettotte 
Good work on all the recent fixes/enhancements.

I recently found another example of the quote mark causing a comment issue.
If the RPG has a fixed format block mixed inside a free format, the comment issue occurs:

![image](https://user-images.githubusercontent.com/18596216/110105553-710f4e80-7da0-11eb-9530-2827981065f3.png)

I appreciate this is generally bad practice and shouldn't be done - but there are also sorts of gremlins in some legacy code :-)

**Comment by CraigMcloughlin** [comment]
Also found an example in comments for procedures:
![image](https://user-images.githubusercontent.com/18596216/110111057-a53a3d80-7da7-11eb-93e0-6d0f9de74ff6.png)

**Comment by barrettotte** [comment]
Ah darn why did I not explicitly test the original snippet lol? I think I know why this one is still happening, I'll take a look.
Thanks for re-commenting, sorry about that

**Comment by barrettotte** [comment]
@CraigMcloughlin Explicitly added two test cases for this issue. Thank you for reporting, it made me find another bug.
I just released v0.5.8 which should fix this up.
