### ISSUE TITLE
PCML grammar ?

### ISSUE THREAD

**Issue by barrettotte** [barrettotte/vscode-ibmi-languages#71]
I've never used PCML personally, but I've heard of it before.
It seems to be just a flavor of XML, but maybe I could add specialized highlighting for it using https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_73/rzahh/pcmlsyn.htm

I would match file extension ```.pcml``` and build it as a smaller layer over the XML grammar.

Would this be worth casually doing when I find some more spare time?

**Comment by richardschoen** [comment]
I've never used in my year of all things IBM i. I don't know if it's worth putting time into it since it's already XML unless you want to do it for a spare time project.
