### ISSUE TITLE
RPG snippets

### ISSUE THREAD

**Issue by worksofliam** [barrettotte/vscode-ibmi-languages#86]
Do you think creating a snippets JSON for RPG built-in functions and If/Endif blocks would better belong in this repo vs the vscode-ibmi repo?

I think it's a worth investment. I'm happy to create it and PR. Let me know.

**Comment by barrettotte** [comment]
Hmm good question, I don't think I really have strong feelings one way or another.
I guess it would make sense for snippets to get bundled with an extension that already does all the file extension associations.
So it shows up in the feature contributions tab:
![image](https://user-images.githubusercontent.com/15623775/132538055-b4831552-40ce-4930-94c1-b8167eef2c93.png)

That being said, I personally see vscode-ibmi as the ultimate IBMi dev productivity extension, so I could see an argument for putting snippets in there; I think there might already be CL snippets included.

It'd also probably be too overkill to create a separate extension just for snippets. In short, whatever you think feels right I'm totally okay with lol

**Comment by worksofliam** [comment]
Sick sick. Yeah, CL snippets is in there but the extension is currently massive.. so I may move them here also.

Plus, Code for IBM i depends on this on installation so it makes sense to me.
