### ISSUE TITLE
Fall 2021: Enhancements for 7.3 TR11 and 7.4 TR5

### ISSUE THREAD

**Issue by barrettotte** [barrettotte/vscode-ibmi-languages#88]
`%MAXARR`, `%MINARR`, `%FIELDS`, `DEBUG(*CONSTANTS)`

references:

- https://www.rpgpgm.com/2021/09/fall-technology-refreshes-announced.html
- https://www.ibm.com/support/pages/ibm-i-73-tr11-enhancements
- https://www.ibm.com/support/pages/node/6456987

**Comment by chrjorgensen** [comment]
I made this - unaware of your issue! 😆 

See PR #89
